services:
  mysql8:
    image: mysql:8.0
    container_name: mysql
    cpus: 1.0
    mem_limit: 2g
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: '123'
      MYSQL_USER: 'user_test' 
      MYSQL_PASSWORD: '123'
    volumes:
      - ./data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
    networks:
      - test-net
networks:
  test-net:
    external: true
